#!/bin/sh

# A shell script to get gazebo and player running together
# Assumes that for the .world file there is a .world.cfg file

if [ "$1" = "-g" ]
then
    if [ "$2" = "" ]
    then
	world="-g /usr/local/share/gazebo/worlds/pioneer2dxSonars.world"
	config="/usr/local/share/player/config/gazebo.cfg"
    else
	world="-g $2"
	config=$2.cfg
    fi
else
    if [ "$1" = "" ]
    then
	world="/usr/local/share/gazebo/worlds/pioneer2dxSonars.world"
	config="/usr/local/share/player/config/gazebo.cfg"

    else
	world="$1"
	config=$1.cfg
    fi
fi
# Start gazebo
gazebo $world &
gpid=$!
# Wait a sec for it to get started
sleep 1
# Now, start the player layer
player -g default $config &
ppid=$!
# Wait for gazebo to get finish
wait $gpid
# Kill player
kill $ppid
