#!/bin/sh

# A shell script to get gazebo and player running together
# Assumes that for the .world file there is a .world.cfg file

pyropid=$1
shift
config="/usr/local/share/player/config/gazebo.cfg"

if [ "$1" = "-g" ]
then
    if [ "$2" = "" ]
    then
	world="-g /usr/local/share/gazebo/worlds/pioneer2dxGrip.world"
    else
	world="-g $2"
    fi
else
    if [ "$1" = "" ]
    then
	world="/usr/local/share/gazebo/worlds/pioneer2dxGrip.world"
    else
	world="$1"
    fi
fi
# clean up any old starts
rm -rf /tmp/gazebo-$USER*
# Start gazebo
wxgazebo $world &
# Wait a bit for it to get started
sleep 3
# Now, start the player layer
player -g default $config &
# wait for pyro to quit
while ps --noheaders $pyropid && ps --noheaders $gpid; do sleep 1; done > /dev/null
# Kill wxgazebo and player
kill 0
