#!/bin/sh

# Option               Default        Description
# ==================   =============  ========================================
# [-p port_name]       8101           Socket port, or file; /tmp/mySim, for 
#                                     example, if local port
# [-r robot_type]      P2DX           Defines simulated robot; see specific 
#                                     definitions in $ARIA/params/
# [-t port_type]       TCP            Simulator connection port; tcp or local
# [-timeout .1secs]    no timeout     Simulator automatically exits after 
#                                     n seconds of no connection
# [-w worldname.wld]  none            Load a 2-D world (.wld) description file 
#                                     ActivMediaLab.wld, for example
# [-s | -g factor]     none           Grows/Shrinks the simulator window 

/usr/local/Aria/bin/SRIsim -p $(( 8000 + $UID ))  -w office.wld -t tcp
