#!/bin/sh

pyropid=$1
shift
if [ "$1" = "-g" ]
then
    echo "no graphics mode not an option with this simulator"
    shift
fi

# Option               Default        Description
# ==================   =============  ========================================
# [-p port_name]       8101           Socket port, or file; /tmp/mySim, for 
#                                     example, if local port
# [-r robot_type]      P2DX           Defines simulated robot; see specific 
#                                     definitions in $ARIA/params/
# [-t port_type]       TCP            Simulator connection port; tcp or local
# [-timeout .1secs]    no timeout     Simulator automatically exits after 
#                                     n seconds of no connection
# [-w worldname.wld]  none            Load a 2-D world (.wld) description file 
#                                     ActivMediaLab.wld, for example
# [-s | -g factor]     none           Grows/Shrinks the simulator window 

if [ $# -eq 0 ]
then
    world="office.world"
else
    world="$1"
fi
export ARIA=/usr/local/Aria
$ARIA/bin/SRIsim -p $(( 8000 + $UID ))  -w $world -t tcp &
# get aria pid
ppid=$!
# wait for pyro to stop
while ps --noheaders $pyropid; do sleep 1; done > /dev/null
# then kill aria
kill $ppid
