#!/bin/sh

if [ "$1" = "-g" ]
then
    if [ "$2" = "" ]
    then
	world="-g /usr/local/share/gazebo/worlds/everything.world"
    else
	world="-g $2"
    fi
else
    if [ "$1" = "" ]
    then
	world="/usr/local/share/gazebo/worlds/everything.world"
    else
	world="$1"
    fi
fi
config=$world.cfg
echo $config
gazebo $world &
sleep 2
player -g default $config &
