#!/bin/sh

if [ "$1" = "-g" ]
then
    if [ "$2" = "" ]
    then
	world="-g /usr/local/stage/worlds/everything.world"
    else
	world="-g $2"
    fi
else
    if [ "$1" = "" ]
    then
	world="/usr/local/stage/worlds/everything.world"
    else
	world="$1"
    fi
fi
export PATH=$PATH:/usr/local/stage/bin:/usr/local/player/bin
stage $world &
