#!/bin/sh

pyropid=$1
shift
if [ "$1" = "-g" ]
then
    if [ "$2" = "" ]
    then
	world="-g /usr/local/share/stage/worlds/everything.world"
    else
	world="-g $2"
    fi
else
    if [ "$1" = "" ]
    then
	world="/usr/local/share/stage/worlds/everything.world"
    else
	world="$1"
    fi
fi
export PLAYERPATH=$PLAYERPATH:/usr/local/lib:/usr/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/lib
#stage -p $(( 16000 + $UID )) $world &
player $world &
while ps --noheaders $pyropid; do sleep 1; done > /dev/null
# then kill sim
kill 0
