# Main Makefile for the Pyro Python Robotics System
# Please edit Makefile.cfg

include Makefile.cfg

SUBDIRS = camera/bt848 geometry gui/3DArray robot/driver/grid \
	robot/driver/video camera/v4l brain/psom/csom_src \
	tools/cluster 

# Failing subdir: robot/driver/testc

ifeq ($(SAPHIRA),)
else
SUBDIRS += lib robot/driver/saphira 
endif

everything: system/version.py all bin/pyro

include Makefile.src

.PHONY: all tar pyro-$(PYRO_VERSION).tgz cleanall

tar: pyro-$(PYRO_VERSION).tgz

pyro-$(PYRO_VERSION).tgz: Makefile
	mkdir tars || true
	mv *.tgz tars/ || true
	make clean; cd ..; tar cfz pyro-$(PYRO_VERSION).tgz pyro --exclude CVS --exclude tars --exclude test --exclude examples/som --exclude som2 --exclude htmlsom --exclude experiments --exclude data --exclude kRobotClass --exclude simulator --exclude SIM --exclude stuff --exclude misc; mv pyro-$(PYRO_VERSION).tgz pyro; cd -; mv *.tgz tars

system/version.py: Makefile.src
	echo -e "# This file is automatically generated\ndef version():\n\treturn \"$(PYRO_VERSION)\"" > system/version.py

bin/pyro: Makefile.src build/pyro
	echo -e "#!/usr/bin/env python$(PYTHON_VERSION)" > bin/pyro
	cat build/pyro >> bin/pyro
	chmod a+x bin/pyro

cleanall::
	rm -rf `find . | grep \.pyc$$`
	rm -rf `find . | grep ~$$`
