/*
 * FILE : lowlevelmodule.cc
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Build 883)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
/***********************************************************************
 * $Header$
 * swig_lib/python/python.cfg
 *
 * Contains variable linking and pointer type-checking code.
 ************************************************************************/

#include <string.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif
#include "Python.h"

/* Definitions for Windows/Unix exporting */
#if defined(_WIN32) || defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a) __declspec(dllexport) a
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a) a _export
#	else
#	    define SWIGEXPORT(a) a
#	endif
#   endif
#else
#   define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGSTATICRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGSTATICRUNTIME(a) static a
#endif

typedef struct {
  char  *name;
  PyObject *(*get_attr)(void);
  int (*set_attr)(PyObject *);
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar **vars;
  int      nvars;
  int      maxvars;
} swig_varlinkobject;

/* ----------------------------------------------------------------------
   swig_varlink_repr()

   Function for python repr method
   ---------------------------------------------------------------------- */

static PyObject *
swig_varlink_repr(swig_varlinkobject *v)
{
  v = v;
  return PyString_FromString("<Global variables>");
}

/* ---------------------------------------------------------------------
   swig_varlink_print()

   Print out all of the global variable names
   --------------------------------------------------------------------- */

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags)
{

  int i = 0;
  flags = flags;
  fprintf(fp,"Global variables { ");
  while (v->vars[i]) {
    fprintf(fp,"%s", v->vars[i]->name);
    i++;
    if (v->vars[i]) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

/* --------------------------------------------------------------------
   swig_varlink_getattr
 
   This function gets the value of a variable and returns it as a
   PyObject.   In our case, we'll be looking at the datatype and
   converting into a number or string
   -------------------------------------------------------------------- */

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n)
{
  int i = 0;
  char temp[128];

  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->get_attr)();
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return NULL;
}

/* -------------------------------------------------------------------
   swig_varlink_setattr()

   This function sets the value of a variable.
   ------------------------------------------------------------------- */

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p)
{
  char temp[128];
  int i = 0;
  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->set_attr)(p);
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return 1;
}

statichere PyTypeObject varlinktype = {
/*  PyObject_HEAD_INIT(&PyType_Type)  Note : This doesn't work on some machines */
  PyObject_HEAD_INIT(0)              
  0,
  "varlink",                          /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */

SWIGSTATICRUNTIME(PyObject *)
SWIG_newvarlink(void)
{
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  /*  _Py_NewReference(result);  Does not seem to be necessary */
  result->nvars = 0;
  result->maxvars = 64;
  result->vars = (swig_globalvar **) malloc(64*sizeof(swig_globalvar *));
  result->vars[0] = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGSTATICRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p))
{
  swig_varlinkobject *v;
  v= (swig_varlinkobject *) p;
	
  if (v->nvars >= v->maxvars -1) {
    v->maxvars = 2*v->maxvars;
    v->vars = (swig_globalvar **) realloc(v->vars,v->maxvars*sizeof(swig_globalvar *));
    if (v->vars == NULL) {
      fprintf(stderr,"SWIG : Fatal error in initializing Python module.\n");
      exit(1);
    }
  }
  v->vars[v->nvars] = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  v->vars[v->nvars]->name = (char *) malloc(strlen(name)+1);
  strcpy(v->vars[v->nvars]->name,name);
  v->vars[v->nvars]->get_attr = get_attr;
  v->vars[v->nvars]->set_attr = set_attr;
  v->nvars++;
  v->vars[v->nvars] = 0;
}

/* -----------------------------------------------------------------------------
 * Pointer type-checking
 * ----------------------------------------------------------------------------- */

/* SWIG pointer structure */
typedef struct SwigPtrType {
  char               *name;               /* Datatype name                  */
  int                 len;                /* Length (used for optimization) */
  void               *(*cast)(void *);    /* Pointer casting function       */
  struct SwigPtrType *next;               /* Linked list pointer            */
} SwigPtrType;

/* Pointer cache structure */
typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static int SwigStart[256];             /* Starting positions of types            */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */

/* Cached values */
#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Register a new datatype with the type-checker */
SWIGSTATICRUNTIME(void) 
SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {
  int i;
  SwigPtrType *t = 0,*t1;

  /* Allocate the pointer table if necessary */
  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
  }

  /* Grow the table */
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc((char *) SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++) {
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN++];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
  }

  /* Check for existing entries */
  while (t->next) {
    if ((strcmp(t->name,newtype) == 0)) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;            
  t->next = t1;           
  SwigPtrSort = 0;
}

/* Make a pointer value string */
SWIGSTATICRUNTIME(void) 
SWIG_MakePtr(char *c, const void *ptr, char *type) {
  static char hex[17] = "0123456789abcdef";
  unsigned long p, s;
  char result[24], *r; 
  r = result;
  p = (unsigned long) ptr;
  if (p > 0) {
    while (p > 0) {
      s = p & 0xf;
      *(r++) = hex[s];
      p = p >> 4;
    }
    *r = '_';
    while (r >= result)
      *(c++) = *(r--);
    strcpy (c, type);
  } else {
    strcpy (c, "NULL");
  }
}

/* Function for getting a pointer value */
SWIGSTATICRUNTIME(char *) 
SWIG_GetPtr(char *c, void **ptr, char *t)
{
  unsigned long p;
  char temp_type[256], *name;
  int  i, len, start, end;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;
  register int d;

  p = 0;
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) return (char *) 0;
    else c;
  }
  c++;
  /* Extract hex value from pointer */
  while (d = *c) {
    if ((d >= '0') && (d <= '9'))
      p = (p << 4) + (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      p = (p << 4) + (d - ('a'-10));
    else
      break; 
    c++;
  }
  *ptr = (void *) p;
  if ((!t) || (strcmp(t,c)==0)) return (char *) 0;

  if (!SwigPtrSort) {
    qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort); 
    for (i = 0; i < 256; i++) SwigStart[i] = SwigPtrN;
    for (i = SwigPtrN-1; i >= 0; i--) SwigStart[(int) (SwigPtrTable[i].name[1])] = i;
    for (i = 255; i >= 1; i--) {
      if (SwigStart[i-1] > SwigStart[i])
	SwigStart[i-1] = SwigStart[i];
    }
    SwigPtrSort = 1;
    for (i = 0; i < SWIG_CACHESIZE; i++) SwigCache[i].stat = 0;
  }
  /* First check cache for matches.  Uses last cache value as starting point */
  cache = &SwigCache[SwigLastCache];
  for (i = 0; i < SWIG_CACHESIZE; i++) {
    if (cache->stat && (strcmp(t,cache->name) == 0) && (strcmp(c,cache->mapped) == 0)) {
      cache->stat++;
      if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
      return (char *) 0;
    }
    SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
    if (!SwigLastCache) cache = SwigCache;
    else cache++;
  }
  /* Type mismatch.  Look through type-mapping table */
  start = SwigStart[(int) t[1]];
  end = SwigStart[(int) t[1]+1];
  sp = &SwigPtrTable[start];

  /* Try to find a match */
  while (start <= end) {
    if (strncmp(t,sp->name,sp->len) == 0) {
      name = sp->name;
      len = sp->len;
      tp = sp->next;
      /* Try to find entry for our given datatype */
      while(tp) {
	if (tp->len >= 255) {
	  return c;
	}
	strcpy(temp_type,tp->name);
	strncat(temp_type,t+len,255-tp->len);
	if (strcmp(c,temp_type) == 0) {
	  strcpy(SwigCache[SwigCacheIndex].mapped,c);
	  strcpy(SwigCache[SwigCacheIndex].name,t);
	  SwigCache[SwigCacheIndex].stat = 1;
	  SwigCache[SwigCacheIndex].tp = tp;
	  SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
	  /* Get pointer value */
	  *ptr = (void *) p;
	  if (tp->cast) *ptr = (*(tp->cast))(*ptr);
	  return (char *) 0;
	}
	tp = tp->next;
      }
    }
    sp++;
    start++;
  }
  return c;
} 

/* New object-based GetPointer function. This uses the Python abstract
 * object interface to automatically dereference the 'this' attribute
 * of shadow objects. */

SWIGSTATICRUNTIME(char *)
SWIG_GetPtrObj(PyObject *obj, void **ptr, char *type) {
  PyObject *sobj = obj;
  char     *str;
  if (!PyString_Check(obj)) {
    sobj = PyObject_GetAttrString(obj,"this");
    if (!sobj) return "";
  }
  str = PyString_AsString(sobj);
  return SWIG_GetPtr(str,ptr,type);
}

#ifdef __cplusplus
}
#endif


#define SWIG_init    initlowlevel

#define SWIG_name    "lowlevel"
 
#include"Saphira.h"
#ifdef __cplusplus
extern "C" {
#endif
#define SFData_x_set(_swigobj,_swigval) (_swigobj->x = _swigval,_swigval)
static PyObject *_wrap_SFData_x_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    SFData * _arg0;
    double  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Od:SFData_x_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_SFData_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of SFData_x_set. Expected _SFData_p.");
        return NULL;
        }
    }
    _result = (double )SFData_x_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define SFData_x_get(_swigobj) ((double ) _swigobj->x)
static PyObject *_wrap_SFData_x_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    SFData * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:SFData_x_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_SFData_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of SFData_x_get. Expected _SFData_p.");
        return NULL;
        }
    }
    _result = (double )SFData_x_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define SFData_y_set(_swigobj,_swigval) (_swigobj->y = _swigval,_swigval)
static PyObject *_wrap_SFData_y_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    SFData * _arg0;
    double  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Od:SFData_y_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_SFData_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of SFData_y_set. Expected _SFData_p.");
        return NULL;
        }
    }
    _result = (double )SFData_y_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define SFData_y_get(_swigobj) ((double ) _swigobj->y)
static PyObject *_wrap_SFData_y_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    SFData * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:SFData_y_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_SFData_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of SFData_y_get. Expected _SFData_p.");
        return NULL;
        }
    }
    _result = (double )SFData_y_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define SFData_z_set(_swigobj,_swigval) (_swigobj->z = _swigval,_swigval)
static PyObject *_wrap_SFData_z_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    SFData * _arg0;
    double  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Od:SFData_z_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_SFData_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of SFData_z_set. Expected _SFData_p.");
        return NULL;
        }
    }
    _result = (double )SFData_z_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define SFData_z_get(_swigobj) ((double ) _swigobj->z)
static PyObject *_wrap_SFData_z_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    SFData * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:SFData_z_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_SFData_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of SFData_z_get. Expected _SFData_p.");
        return NULL;
        }
    }
    _result = (double )SFData_z_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define SFData_range_set(_swigobj,_swigval) (_swigobj->range = _swigval,_swigval)
static PyObject *_wrap_SFData_range_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    SFData * _arg0;
    double  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Od:SFData_range_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_SFData_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of SFData_range_set. Expected _SFData_p.");
        return NULL;
        }
    }
    _result = (double )SFData_range_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define SFData_range_get(_swigobj) ((double ) _swigobj->range)
static PyObject *_wrap_SFData_range_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    SFData * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:SFData_range_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_SFData_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of SFData_range_get. Expected _SFData_p.");
        return NULL;
        }
    }
    _result = (double )SFData_range_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define SFData_flag_set(_swigobj,_swigval) (_swigobj->flag = _swigval,_swigval)
static PyObject *_wrap_SFData_flag_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    SFData * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:SFData_flag_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_SFData_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of SFData_flag_set. Expected _SFData_p.");
        return NULL;
        }
    }
    _result = (int )SFData_flag_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define SFData_flag_get(_swigobj) ((int ) _swigobj->flag)
static PyObject *_wrap_SFData_flag_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    SFData * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:SFData_flag_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_SFData_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of SFData_flag_get. Expected _SFData_p.");
        return NULL;
        }
    }
    _result = (int )SFData_flag_get(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define new_Saphira() (new Saphira())
static PyObject *_wrap_new_Saphira(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    Saphira * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":new_Saphira")) 
        return NULL;
    _result = (Saphira *)new_Saphira();
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_Saphira_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

#define delete_Saphira(_swigobj) (delete _swigobj)
static PyObject *_wrap_delete_Saphira(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    Saphira * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:delete_Saphira",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of delete_Saphira. Expected _Saphira_p.");
        return NULL;
        }
    }
    delete_Saphira(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define Saphira__getSonarRange(_swigobj,_swigarg0)  (_swigobj->_getSonarRange(_swigarg0))
static PyObject *_wrap_Saphira__getSonarRange(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Saphira * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:Saphira__getSonarRange",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira__getSonarRange. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (double )Saphira__getSonarRange(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Saphira__getSonarXCoord(_swigobj,_swigarg0)  (_swigobj->_getSonarXCoord(_swigarg0))
static PyObject *_wrap_Saphira__getSonarXCoord(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Saphira * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:Saphira__getSonarXCoord",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira__getSonarXCoord. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (double )Saphira__getSonarXCoord(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Saphira__getSonarYCoord(_swigobj,_swigarg0)  (_swigobj->_getSonarYCoord(_swigarg0))
static PyObject *_wrap_Saphira__getSonarYCoord(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Saphira * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:Saphira__getSonarYCoord",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira__getSonarYCoord. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (double )Saphira__getSonarYCoord(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Saphira_getSonarRange(_swigobj,_swigarg0)  (_swigobj->getSonarRange(_swigarg0))
static PyObject *_wrap_Saphira_getSonarRange(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Saphira * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:Saphira_getSonarRange",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_getSonarRange. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (double )Saphira_getSonarRange(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Saphira_getSonarXCoord(_swigobj,_swigarg0)  (_swigobj->getSonarXCoord(_swigarg0))
static PyObject *_wrap_Saphira_getSonarXCoord(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Saphira * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:Saphira_getSonarXCoord",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_getSonarXCoord. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (double )Saphira_getSonarXCoord(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Saphira_getSonarYCoord(_swigobj,_swigarg0)  (_swigobj->getSonarYCoord(_swigarg0))
static PyObject *_wrap_Saphira_getSonarYCoord(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Saphira * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:Saphira_getSonarYCoord",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_getSonarYCoord. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (double )Saphira_getSonarYCoord(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Saphira_SonarData_set(_swigobj,_swigval) (_swigobj->SonarData = _swigval,_swigval)
static PyObject *_wrap_Saphira_SonarData_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    SFData * _result;
    Saphira * _arg0;
    SFData * _arg1;
    PyObject * _argo0 = 0;
    PyObject * _argo1 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"OO:Saphira_SonarData_set",&_argo0,&_argo1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_SonarData_set. Expected _Saphira_p.");
        return NULL;
        }
    }
    if (_argo1) {
        if (_argo1 == Py_None) { _arg1 = NULL; }
        else if (SWIG_GetPtrObj(_argo1,(void **) &_arg1,"_SFData_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of Saphira_SonarData_set. Expected _SFData_p.");
        return NULL;
        }
    }
    _result = (SFData *)Saphira_SonarData_set(_arg0,_arg1);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_SFData_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

#define Saphira_SonarData_get(_swigobj) ((SFData *) _swigobj->SonarData)
static PyObject *_wrap_Saphira_SonarData_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    SFData * _result;
    Saphira * _arg0;
    PyObject * _argo0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"O:Saphira_SonarData_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_SonarData_get. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (SFData *)Saphira_SonarData_get(_arg0);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_SFData_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

#define Saphira_getX(_swigobj)  (_swigobj->getX())
static PyObject *_wrap_Saphira_getX(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Saphira * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:Saphira_getX",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_getX. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (double )Saphira_getX(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Saphira_getY(_swigobj)  (_swigobj->getY())
static PyObject *_wrap_Saphira_getY(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Saphira * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:Saphira_getY",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_getY. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (double )Saphira_getY(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Saphira_getZ(_swigobj)  (_swigobj->getZ())
static PyObject *_wrap_Saphira_getZ(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Saphira * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:Saphira_getZ",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_getZ. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (double )Saphira_getZ(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Saphira_getTh(_swigobj)  (_swigobj->getTh())
static PyObject *_wrap_Saphira_getTh(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Saphira * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:Saphira_getTh",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_getTh. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (double )Saphira_getTh(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Saphira_getThr(_swigobj)  (_swigobj->getThr())
static PyObject *_wrap_Saphira_getThr(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Saphira * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:Saphira_getThr",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_getThr. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (double )Saphira_getThr(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Saphira_Disconnect(_swigobj)  (_swigobj->Disconnect())
static PyObject *_wrap_Saphira_Disconnect(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Saphira * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:Saphira_Disconnect",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_Disconnect. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (int )Saphira_Disconnect(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define Saphira_Connect(_swigobj,_swigarg0)  (_swigobj->Connect(_swigarg0))
static PyObject *_wrap_Saphira_Connect(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Saphira * _arg0;
    int  _arg1 = (int ) 1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O|i:Saphira_Connect",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_Connect. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (int )Saphira_Connect(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define Saphira_Move(_swigobj,_swigarg0,_swigarg1)  (_swigobj->Move(_swigarg0,_swigarg1))
static PyObject *_wrap_Saphira_Move(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Saphira * _arg0;
    double  _arg1;
    double  _arg2;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Odd:Saphira_Move",&_argo0,&_arg1,&_arg2)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_Move. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (int )Saphira_Move(_arg0,_arg1,_arg2);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define Saphira_Rotate(_swigobj,_swigarg0)  (_swigobj->Rotate(_swigarg0))
static PyObject *_wrap_Saphira_Rotate(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Saphira * _arg0;
    double  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Od:Saphira_Rotate",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_Rotate. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (int )Saphira_Rotate(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define Saphira_Translate(_swigobj,_swigarg0)  (_swigobj->Translate(_swigarg0))
static PyObject *_wrap_Saphira_Translate(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Saphira * _arg0;
    double  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Od:Saphira_Translate",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_Translate. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (int )Saphira_Translate(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define Saphira_IsStall(_swigobj)  (_swigobj->IsStall())
static PyObject *_wrap_Saphira_IsStall(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Saphira * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:Saphira_IsStall",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_IsStall. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (int )Saphira_IsStall(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define Saphira_UpdatePosition(_swigobj)  (_swigobj->UpdatePosition())
static PyObject *_wrap_Saphira_UpdatePosition(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Saphira * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:Saphira_UpdatePosition",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_UpdatePosition. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (int )Saphira_UpdatePosition(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define Saphira_UpdateReading(_swigobj,_swigarg0)  (_swigobj->UpdateReading(_swigarg0))
static PyObject *_wrap_Saphira_UpdateReading(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    Saphira * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:Saphira_UpdateReading",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_UpdateReading. Expected _Saphira_p.");
        return NULL;
        }
    }
    Saphira_UpdateReading(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define Saphira_UpdateReadings(_swigobj)  (_swigobj->UpdateReadings())
static PyObject *_wrap_Saphira_UpdateReadings(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    Saphira * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:Saphira_UpdateReadings",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_UpdateReadings. Expected _Saphira_p.");
        return NULL;
        }
    }
    Saphira_UpdateReadings(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define Saphira_Localize(_swigobj,_swigarg0,_swigarg1,_swigarg2)  (_swigobj->Localize(_swigarg0,_swigarg1,_swigarg2))
static PyObject *_wrap_Saphira_Localize(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    Saphira * _arg0;
    double  _arg1;
    double  _arg2;
    double  _arg3;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oddd:Saphira_Localize",&_argo0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_Localize. Expected _Saphira_p.");
        return NULL;
        }
    }
    Saphira_Localize(_arg0,_arg1,_arg2,_arg3);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define Saphira_getSonarCount(_swigobj)  (_swigobj->getSonarCount())
static PyObject *_wrap_Saphira_getSonarCount(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Saphira * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:Saphira_getSonarCount",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_getSonarCount. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (int )Saphira_getSonarCount(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define Saphira_setSonarFlag(_swigobj,_swigarg0,_swigarg1)  (_swigobj->setSonarFlag(_swigarg0,_swigarg1))
static PyObject *_wrap_Saphira_setSonarFlag(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    Saphira * _arg0;
    int  _arg1;
    int  _arg2;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oii:Saphira_setSonarFlag",&_argo0,&_arg1,&_arg2)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_setSonarFlag. Expected _Saphira_p.");
        return NULL;
        }
    }
    Saphira_setSonarFlag(_arg0,_arg1,_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define Saphira_getSonarFlag(_swigobj,_swigarg0)  (_swigobj->getSonarFlag(_swigarg0))
static PyObject *_wrap_Saphira_getSonarFlag(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Saphira * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:Saphira_getSonarFlag",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_getSonarFlag. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (int )Saphira_getSonarFlag(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define Saphira_sonar_th(_swigobj,_swigarg0)  (_swigobj->sonar_th(_swigarg0))
static PyObject *_wrap_Saphira_sonar_th(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Saphira * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:Saphira_sonar_th",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_sonar_th. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (double )Saphira_sonar_th(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Saphira_sonar_x(_swigobj,_swigarg0)  (_swigobj->sonar_x(_swigarg0))
static PyObject *_wrap_Saphira_sonar_x(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Saphira * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:Saphira_sonar_x",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_sonar_x. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (double )Saphira_sonar_x(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Saphira_sonar_y(_swigobj,_swigarg0)  (_swigobj->sonar_y(_swigarg0))
static PyObject *_wrap_Saphira_sonar_y(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Saphira * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:Saphira_sonar_y",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_Saphira_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Saphira_sonar_y. Expected _Saphira_p.");
        return NULL;
        }
    }
    _result = (double )Saphira_sonar_y(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define new_CameraMover() (new CameraMover())
static PyObject *_wrap_new_CameraMover(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    CameraMover * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":new_CameraMover")) 
        return NULL;
    _result = (CameraMover *)new_CameraMover();
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_CameraMover_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

#define delete_CameraMover(_swigobj) (delete _swigobj)
static PyObject *_wrap_delete_CameraMover(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    CameraMover * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:delete_CameraMover",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_CameraMover_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of delete_CameraMover. Expected _CameraMover_p.");
        return NULL;
        }
    }
    delete_CameraMover(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define CameraMover_Init(_swigobj)  (_swigobj->Init())
static PyObject *_wrap_CameraMover_Init(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    CameraMover * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:CameraMover_Init",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_CameraMover_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of CameraMover_Init. Expected _CameraMover_p.");
        return NULL;
        }
    }
    CameraMover_Init(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define CameraMover_Pan(_swigobj,_swigarg0)  (_swigobj->Pan(_swigarg0))
static PyObject *_wrap_CameraMover_Pan(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    CameraMover * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:CameraMover_Pan",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_CameraMover_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of CameraMover_Pan. Expected _CameraMover_p.");
        return NULL;
        }
    }
    CameraMover_Pan(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define CameraMover_Tilt(_swigobj,_swigarg0)  (_swigobj->Tilt(_swigarg0))
static PyObject *_wrap_CameraMover_Tilt(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    CameraMover * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:CameraMover_Tilt",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_CameraMover_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of CameraMover_Tilt. Expected _CameraMover_p.");
        return NULL;
        }
    }
    CameraMover_Tilt(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define CameraMover_PanTilt(_swigobj,_swigarg0,_swigarg1)  (_swigobj->PanTilt(_swigarg0,_swigarg1))
static PyObject *_wrap_CameraMover_PanTilt(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    CameraMover * _arg0;
    int  _arg1;
    int  _arg2;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oii:CameraMover_PanTilt",&_argo0,&_arg1,&_arg2)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_CameraMover_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of CameraMover_PanTilt. Expected _CameraMover_p.");
        return NULL;
        }
    }
    CameraMover_PanTilt(_arg0,_arg1,_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define CameraMover_Zoom(_swigobj,_swigarg0)  (_swigobj->Zoom(_swigarg0))
static PyObject *_wrap_CameraMover_Zoom(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    CameraMover * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:CameraMover_Zoom",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_CameraMover_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of CameraMover_Zoom. Expected _CameraMover_p.");
        return NULL;
        }
    }
    CameraMover_Zoom(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define CameraMover_Center(_swigobj)  (_swigobj->Center())
static PyObject *_wrap_CameraMover_Center(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    CameraMover * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:CameraMover_Center",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_CameraMover_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of CameraMover_Center. Expected _CameraMover_p.");
        return NULL;
        }
    }
    CameraMover_Center(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyMethodDef lowlevelMethods[] = {
	 { "CameraMover_Center", _wrap_CameraMover_Center, METH_VARARGS },
	 { "CameraMover_Zoom", _wrap_CameraMover_Zoom, METH_VARARGS },
	 { "CameraMover_PanTilt", _wrap_CameraMover_PanTilt, METH_VARARGS },
	 { "CameraMover_Tilt", _wrap_CameraMover_Tilt, METH_VARARGS },
	 { "CameraMover_Pan", _wrap_CameraMover_Pan, METH_VARARGS },
	 { "CameraMover_Init", _wrap_CameraMover_Init, METH_VARARGS },
	 { "delete_CameraMover", _wrap_delete_CameraMover, METH_VARARGS },
	 { "new_CameraMover", _wrap_new_CameraMover, METH_VARARGS },
	 { "Saphira_sonar_y", _wrap_Saphira_sonar_y, METH_VARARGS },
	 { "Saphira_sonar_x", _wrap_Saphira_sonar_x, METH_VARARGS },
	 { "Saphira_sonar_th", _wrap_Saphira_sonar_th, METH_VARARGS },
	 { "Saphira_getSonarFlag", _wrap_Saphira_getSonarFlag, METH_VARARGS },
	 { "Saphira_setSonarFlag", _wrap_Saphira_setSonarFlag, METH_VARARGS },
	 { "Saphira_getSonarCount", _wrap_Saphira_getSonarCount, METH_VARARGS },
	 { "Saphira_Localize", _wrap_Saphira_Localize, METH_VARARGS },
	 { "Saphira_UpdateReadings", _wrap_Saphira_UpdateReadings, METH_VARARGS },
	 { "Saphira_UpdateReading", _wrap_Saphira_UpdateReading, METH_VARARGS },
	 { "Saphira_UpdatePosition", _wrap_Saphira_UpdatePosition, METH_VARARGS },
	 { "Saphira_IsStall", _wrap_Saphira_IsStall, METH_VARARGS },
	 { "Saphira_Translate", _wrap_Saphira_Translate, METH_VARARGS },
	 { "Saphira_Rotate", _wrap_Saphira_Rotate, METH_VARARGS },
	 { "Saphira_Move", _wrap_Saphira_Move, METH_VARARGS },
	 { "Saphira_Connect", _wrap_Saphira_Connect, METH_VARARGS },
	 { "Saphira_Disconnect", _wrap_Saphira_Disconnect, METH_VARARGS },
	 { "Saphira_getThr", _wrap_Saphira_getThr, METH_VARARGS },
	 { "Saphira_getTh", _wrap_Saphira_getTh, METH_VARARGS },
	 { "Saphira_getZ", _wrap_Saphira_getZ, METH_VARARGS },
	 { "Saphira_getY", _wrap_Saphira_getY, METH_VARARGS },
	 { "Saphira_getX", _wrap_Saphira_getX, METH_VARARGS },
	 { "Saphira_SonarData_get", _wrap_Saphira_SonarData_get, METH_VARARGS },
	 { "Saphira_SonarData_set", _wrap_Saphira_SonarData_set, METH_VARARGS },
	 { "Saphira_getSonarYCoord", _wrap_Saphira_getSonarYCoord, METH_VARARGS },
	 { "Saphira_getSonarXCoord", _wrap_Saphira_getSonarXCoord, METH_VARARGS },
	 { "Saphira_getSonarRange", _wrap_Saphira_getSonarRange, METH_VARARGS },
	 { "Saphira__getSonarYCoord", _wrap_Saphira__getSonarYCoord, METH_VARARGS },
	 { "Saphira__getSonarXCoord", _wrap_Saphira__getSonarXCoord, METH_VARARGS },
	 { "Saphira__getSonarRange", _wrap_Saphira__getSonarRange, METH_VARARGS },
	 { "delete_Saphira", _wrap_delete_Saphira, METH_VARARGS },
	 { "new_Saphira", _wrap_new_Saphira, METH_VARARGS },
	 { "SFData_flag_get", _wrap_SFData_flag_get, METH_VARARGS },
	 { "SFData_flag_set", _wrap_SFData_flag_set, METH_VARARGS },
	 { "SFData_range_get", _wrap_SFData_range_get, METH_VARARGS },
	 { "SFData_range_set", _wrap_SFData_range_set, METH_VARARGS },
	 { "SFData_z_get", _wrap_SFData_z_get, METH_VARARGS },
	 { "SFData_z_set", _wrap_SFData_z_set, METH_VARARGS },
	 { "SFData_y_get", _wrap_SFData_y_get, METH_VARARGS },
	 { "SFData_y_set", _wrap_SFData_y_set, METH_VARARGS },
	 { "SFData_x_get", _wrap_SFData_x_get, METH_VARARGS },
	 { "SFData_x_set", _wrap_SFData_x_set, METH_VARARGS },
	 { NULL, NULL }
};
#ifdef __cplusplus
}
#endif
/*
 * This table is used by the pointer type-checker
 */
static struct { char *n1; char *n2; void *(*pcnv)(void *); } _swig_mapping[] = {
    { "_signed_long","_long",0},
    { "_long","_unsigned_long",0},
    { "_long","_signed_long",0},
    { "_class_Saphira","_Saphira",0},
    { "_class_CameraMover","_CameraMover",0},
    { "_unsigned_long","_long",0},
    { "_signed_int","_int",0},
    { "_unsigned_short","_short",0},
    { "_signed_short","_short",0},
    { "_SFData","_class_SFData",0},
    { "_unsigned_int","_int",0},
    { "_short","_unsigned_short",0},
    { "_short","_signed_short",0},
    { "_int","_unsigned_int",0},
    { "_int","_signed_int",0},
    { "_class_SFData","_SFData",0},
    { "_CameraMover","_class_CameraMover",0},
    { "_Saphira","_class_Saphira",0},
{0,0,0}};

static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void) initlowlevel() {
	 PyObject *m, *d;
	 SWIG_globals = SWIG_newvarlink();
	 m = Py_InitModule("lowlevel", lowlevelMethods);
	 d = PyModule_GetDict(m);
{
   int i;
   for (i = 0; _swig_mapping[i].n1; i++)
        SWIG_RegisterMapping(_swig_mapping[i].n1,_swig_mapping[i].n2,_swig_mapping[i].pcnv);
}
}
