#!/bin/csh
#
# set umask to access pipe /tmp/robot
# then start Pioneer simulator

# Didn't know csh was so brain-dead
setenv PATH /bin:/usr/bin:${PATH}

if (! $?SAPHIRA) then
echo "***" Setting SAPHIRA to /usr/local/saphira
setenv SAPHIRA /usr/local/saphira/ver62
endif

if (! -d $SAPHIRA) then
echo SAPHIRA is not set to a directory
exit
endif

if(! $?SAPHIRA_COMPIPE) then
echo "***" Setting SAPHIRA_COMPIPE to /tmp/$LOGNAME
setenv SAPHIRA_COMPIPE /tmp/$LOGNAME
endif
 
setenv XXX `umask`
umask 000
echo Starting Pioneer simulator
${SAPHIRA}/bin/spio_exe $1 &
umask ${XXX}
echo Started
